name: compositeaction
description: hai from composite
runs:
  using: "composite"
  steps:
  - name: step1
    run: echo "step1"
    shell: bash
  - name: step2
    run: echo "step2"
    shell: bash