name: compositeaction
description: hai from composite
inputs:
  in1:
    description: in1
    type: string
    required: true
outputs:
  output1:
    description: "hai bro"
    value: ${{ steps.id1.outputs.var1 }}  # This correctly references the output variable
runs:
  using: "composite"
  steps:
    - name: step1
      id: id1
      run: echo "var1=hello123" >> $GITHUB_OUTPUT  # Ensure this is correct
      shell: bash
    - name: step2
      run: echo "step2 using in1 as ${{ inputs.in1 }}"
      shell: bash
