name: anc
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: compositeaction
      id: uu
      uses: asif741852014/compositeaction@v1.0.0
    - run: echo "hai ${{ steps.uu.outputs.output1 }}"
            
    
