name: anc
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: compositeaction
        id: uu
        uses: ./
      - run: echo "hai ${{ steps.uu.outputs.output1 }}"  # This will output 'hai hello'
